In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/Users/christianmonsalve/Desktop/CODE/Projects/Movie_Recs/data/processed/new_movie_features.csv')

In [3]:
data = data.loc[:, 'tconst': 'year'].query('year > 1960')

In [4]:
data.shape

(639070, 3)

In [6]:
data[data.primaryTitle.str.startswith("Us")]

           tconst                     primaryTitle  year
40265   tt0055579       Usted puede ser un asesino  1961
41118   tt0056642  Usted tiene ojos de mujer fatal  1962
41909   tt0057630                              Uso  1963
48381   tt0066514                        Uski Roti  1970
57631   tt0080069                         Usijanje  1979
...           ...                              ...   ...
721205  tt9033306             Ushinawareta ecstasy  1971
723290  tt9130514                      Us vs. Them  2014
733801  tt9767586                           Uspekh  2019
736147  tt9900908                Useless Handcuffs  1969
736298  tt9909716                      Ushiro muki  1981

[237 rows x 3 columns]

In [7]:
ids = ['tt0892769', 'tt1646971', 'tt2386490', 'tt0120338', 'tt0499549', 'tt1630029', 'tt0120915',
       'tt0121765', 'tt0121766', 'tt0076759', 'tt0080684', 'tt0086190', 'tt2488496', 'tt2527336',
       'tt2527338', 'tt30144839', 'tt0120812', 'tt0266915', 'tt0293564', 'tt0371746', 'tt1228705',
       'tt1300854', 'tt0800369', 'tt0458339', 'tt14513804', 'tt1843866', 'tt3498820', 'tt0848228',
       'tt1981115', 'tt2015381', 'tt3896198', 'tt6791350', 'tt2395427', 'tt0478970', 'tt1211837',
       'tt9419884', 'tt2250912', 'tt3501632', 'tt1825683', 'tt9114286', 'tt10954600', 'tt5095030',
       'tt4154664', 'tt4154796', 'tt6320628', 'tt3480822', 'tt9376612', 'tt9032400', 'tt10872600',
       'tt10648342', 'tt1431045', 'tt5463162', 'tt6263850', 'tt20969586', 'tt10676052', 'tt15671028',
       'tt20215968', 'tt1618434', 'tt15255288', 'tt11564570', 'tt8946378', 'tt26047818', 'tt0119654',
       'tt0120912', 'tt1409024', 'tt2283336', 'tt2802144', 'tt4649466', 'tt6856242', 'tt1298644',
       'tt31193180', 'tt7286456', 'tt0468569', 'tt1232829', 'tt1677720', 'tt14205554', 'tt0816711',
       'tt0137523', 'tt0172495', 'tt4633694', 'tt11032374', 'tt32820897', 'tt8430862', 'tt5164214', 
       'tt1041829', 'tt2704998', 'tt4154756', 'tt18412256']

In [8]:
print(len(ids))

88

In [9]:
user_ratings = data[data['tconst'].isin(ids)].sort_values(by='year')

In [10]:
user_ratings.iloc[60]

tconst           tt1298644
primaryTitle    The Hustle
year                  2019
Name: 289382, dtype: object

In [11]:
ratings = [5.0, 6.0, 5.5, 3.5, 8.0, 5.0, 7.5, 6.0, 8.5, 7.0,
           7.0, 8.0, 9.0, 7.0, 5.0, 6.0, 7.5, 4.0, 8.0, 8.0,
           6.0, 8.5, 6.0, 6.5, 5.0, 8.5, 6.5, 7.0, 8.5, 7.0,
           5.0, 7.0, 6.0, 7.0, 8.0, 7.5, 8.5, 4.5, 7.5, 6.0,
           7.0, 9.0, 2.0, 4.5, 9.0, 7.5, 8.5, 9.0, 7.5, 5.0,
           5.5, 7.5, 4.5, 6.0, 9.0, 4.5, 9.5, 7.5, 5.0, 6.0,
           4.5, 7.0, 7.0, 8.0, 7.5, 7.5, 9.7, 8.0, 7.5, 7.5,
           6.0, 8.0, 9.0, 8.5, 4.0, 7.0, 8.5, 5.5, 7.5, 8.5,
           7.5, 9.5, 7.0, 7.5, 8.0, 4.5, 8.5, 3.5]

In [12]:
print(len(ratings))

88

In [13]:
sum(ratings) / len(ratings)

6.8715909090909095

In [14]:
user_ratings['userRating'] = ratings

In [15]:
user_ratings.head()

,tconst,primaryTitle,year,userRating
55409,tt0076759,Star Wars: Episode IV - A New Hope,1977,5.0
58004,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980,6.0
61740,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983,5.5
81705,tt0119654,Men in Black,1997,3.5
82141,tt0120338,Titanic,1997,8.0

In [16]:
user_ratings = user_ratings.drop(columns=['primaryTitle', 'year'])

In [18]:
user_ratings['user_id'] = 1

In [19]:
user_ratings.head()

          tconst  userRating  user_id
55409  tt0076759         5.0        1
58004  tt0080684         6.0        1
61740  tt0086190         5.5        1
81705  tt0119654         3.5        1
82141  tt0120338         8.0        1

In [25]:
user_ratings.to_csv('/Users/christianmonsalve/Desktop/CODE/Projects/Movie_Recs/user_data/user_data.csv', index=False)